---
title: 'Productivity Tools Section 1: Installing Software'
author: "Erin Lloyd"
date: "29/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.1 Installing R and RStudio

### Installing Software

We will install:

* R: the programming language we use to analyse data  

* RStudio: the integrated desktop environment we use to edit, organize, and test R scripts  

* Git (and Git Bash for Windows): version control system  


### Installing R

You need to install R before using RStudio, which is an interactive desktop environment.  

Select base subdirectory in CRAN and click download.  

Select all default choices in the installation process.  

We recommend selecting English for language to help you better follow the course.  

One can try using the R console, but for productivity purposes, we can switch to RStudio.  


### Installing RStudio

You can download the latest version of RStudio at the RStudio website External link.  

The free desktop version is more than enough for this course.  

Make sure to choose the version for your own operating system.  

Choose "Yes" for all defaults in the installation process.  


### Using RStudio for the First Time

In Windows, search for Rstudio in "Start"  

In Mac, choose Rstudio from applications, or use Command+Space to use spotlight search to avoid using the mouse  

To start a new script: file > new file > Rscript (or using key bindings: Ctrl+Shift+N on Windows, and Command+Shift+N on Mac)  

Key bindings from Rstudio cheatsheet can be located with Help > cheatsheet > Rstudio IDE cheatsheet  


## 1.2 Introduction to RStudio

### Installing Packages

We will be using **tidyverse** and **dslabs** packages for this course, which do not come preinstalled in base R.  

Install packages from R console: *install.packages("pkg_name")*  

Install packages from Rstudio interface: Tools > install packages (allow autocomplete)  

Once installed, we can use *library("pkg_name")* to load a package each time we want to use it  

Check the packages you have installed  

Good practice: make a script to install all the packages you need for a fresh R  


### Running Commands While Editing Scripts

RStudio has many useful features as an R editor, including the ability to test code easily as we write scripts and several autocomplete features.  

Keyboard shortcuts:  

* Save a script: Ctrl+S on Windows and Command+S on Mac  

* Run an entire script:  Ctrl+Shift+Enter on Windows Command+Shift+Return on Mac, or click "Source" on the editor pane  

* Run a single line of script: Ctrl+Enter on Windows and Command+Return on Mac while the cursor is pointing to that line, or select the chunk and click "run"  

* Open a new script: Ctrl+Shift+N on Windows and Command+Shift+N on Mac  


### Keeping Organized with RStudio Projects

RStudio provides a way to keep all the components of a data analysis project organized into one folder and to keep track of information about this project.  

To start a project, click on File > New Project > New repository > New project > decide the location of files and give a name to the project, e.g. "my-first-project". This will then generate a Rproj file called my-first-project.Rproj in the folder associated with the project, from which you can double click to start where you last left off.  

The project name will appear in the upper left corner or the upper right corner, depending on your operating system. When you start an RStudio session with no project, it will display "Project: (None)".  


## 1.3 Introduction to Git and GitHub

### Installing Git Introduction

Git is a version control system, tracking changes and coordinating the editing of code.  

GitHub is a hosting system for code, which can help with your career profile.  

Git is most effectively used with Unix, but it can also interface with RStudio.  


### Installing Git

#### Install on Mac

Open the terminal, either from the utility folder or using Cmd+space, and check if you already have Git installed by typing *git --version* in the command line.  

If you already have Git installed, you will be shown the version number after executing the above. If you do not have Git installed already, you will be prompted to do so.  


#### Install on Windows

Download Git bash from https://git-scm.com/ External link  

When asked to choose the default editor for Git, we recommend choosing nano if you do not already know VIM.  

The "git and optional Unix tools from Windows" option will allow you to learn Unix from Rstudio, however, it might interfere with the Windows command line.  

Finally, change the Rstudio preference so that you are using Git bash as the terminal (only for Windows user).  


### GitHub

Sign up for a GitHub account, with a name that is professional, short, and easy to remember  

Connect to RStudio: global options > Git/SVM, enter the path to git executables  

To avoid typing our GitHub password every time, we create a SSH/RSA key automatically through RStudio with the create RSA key button.  


### GitHub Repositories

To create a new GitHub repository and link it to an RStudio project, follow 2 steps:  

* Step 1: Initialize a new repo on GitHub by clicking repository > new > choose a descriptive name.  

* Step 2: Connect to RStudio (next video).  


### RStudio, Git, and GitHub

In terminal: configure git   

git config --global user.name "Your Name"  

git config --global user.email "your@email.com"  

In RStudio, create project > Version control > Git  

Git pane: status symbols and color  

Git actions:  

* **pull**: pull changes from remote repo (if you are in collaboration with others)  

* **add**: stage files for commit; click on stage box under git pane  

* **commit**: commit to the local repo; click on "commit" button under git pane; add a commit message  

* **push**: push to the remote repo on Github  

.gitignore file: details check https://git-scm.com/docs/gitignore External link


## Comprehension Check: Installing Software

### Q1

Which of the following statements about R and RStudio is true?  

**Possible Answers**  

* R is a programming language, whereas RStudio is a desktop environment.  

* You can use RStudio without using R, but we recommend using R in this course.  

* When you download RStudio, it automatically downloads and installs R too.  

* You can only use R on Mac OS X and Linux. Windows users must use RStudio.  

**ANSWER: **  


### Q2
Which of the following is not true about installing packages? *Select ALL that apply.*  

**Possible Answers**  

* To install a new package, the install.packages() function can be used  

* To install a new package, the drop-down menu Tools > Install packages can be used  

* Installed packages will remain installed even if you upgrade R  

* Installing a package by building from GitHub will give you the exact same version as on CRAN  

**ANSWER: **  


### Q3
Which of the following commands for editing scripts is not correct?  

**Possible Answers**  

* To save a script: Ctrl+S on Windows/Linux / Command+S on Mac  

* To run an entire script: Ctrl+Shift+Enter on Windows/Linux / Command+Shift+Return on Mac, or click “Source” on the editor pane.  

* To open a new script: Ctrl+Shift+N on Windows/Linux / Command+Shift+N on Mac  

* To run a single line of script: Ctrl+Shift / Command+Shift while cursor pointing to that line, or select the chunk and click "run"  

* To comment selected text: Ctrl+Shift+C or Command+Shift+C for Mac.  

**ANSWER: **  


### Q4

Which of the following statements about keeping organized with RStudio projects is not correct?  

**Possible Answers**  

* To start a new project, click on File > New Project > New directory > New project > {choose a file directory and project name}  

* You must always start a project in a new directory.  

* RStudio provides a way to keep all components of a data analysis project organized into one folder and to keep track of information about this project.  

* Creating a new R project will produce an .Rproj file associated with the project.  

**ANSWER: **  


### Q5

What can you change in the global options? *Select ALL that apply.*  

**Possible Answers**  

* Set Git / GitHub configuration for each R project  

* Move the editor pane to the upper right  

* Change the editor theme to a dark background  

* Customize key binding  

**ANSWER: **  


### Q6

What does the term "pull" mean in the context of using Git in RStudio?  

**Possible Answers**  

* Add local files to a remote GitHub repo.  

* Download changes from the remote repo to your local repository.  

* Configure the RStudio environment to automatically connect to GitHub.  

* Save changes made in RStudio to the local repository on your computer.  

**ANSWER: **  


### Q7

What does the term “push” mean in the context of using Git in RStudio?  

**Possible Answers**  

* Upload changes made in your local repository to a remote repository.  

* Download changes from the remote repo to the RStudio environment.  

* Configure the RStudio environment to automatically connect to GitHub.  

* Save changes made in RStudio to the local repository on your computer.  

**ANSWER: **  


### Q8

What does the term “commit” mean in the context of using Git in RStudio?  

**Possible Answers**  

* Add local files to a remote GitHub repo.  

* Download changes from the remote repo to the RStudio environment.  

* Configure the RStudio environment to automatically connect to GitHub.  

* Save changes made in RStudio to the local repository on your computer.  

**ANSWER: **  


### Q9

Did you create a GitHub account? Enter your GitHub username below.  

**ANSWER: elloyd31**  

