---
title: 'Productivity Tools Section 4: Git and GitHub'
author: "Erin Lloyd"
date: "29/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4.1 Git and GitHub

### Git and GitHub

Next, we will learn how to use Git and GitHub in the command line.  

Reasons to use Git and GitHub:  

* Version-control: Permits us to keep track of changes we made to code, to revert back to previous versions of files, to test ideas using new branches and decide if we want to merge to the original.  

* Collaboration: On a centralized repo, multiple people may make changes to the code and keep versions synced. A pull request allows anyone to suggest changes to your code.  

* Sharing code  

To effectively permit version control and collaboration, files move across four different areas: Working Directory, Staging Area, Local Repository, and Upstream Repository.  

Start your Git journey with either cloning an existing repo, or initializing a new one.  

### Using Git at the Command Line

Recap: there are four stages: working directory, staging area, local repository, and upstream repository  

Clone an existing upstream repository (copy repo url from clone button, and type "*git clone <url>*"), and all three local stages are the same as upstream remote.  

The working directory is the same as the working directory in Rstudio. When we edit files we only change the files in this place.  

*git status*: tells how the files in the working directory are related to the files in other stages  

edits in the staging area are not tracked by the version control system by default - we add a file to the staging area by *git add* command  

*git commit*: to commit files from the staging area to local repository, we need to add a message stating what we are doing by *git commit -m "something"*  

*git log*: keeps track of all the changes we have made to the local repository  

*git push*: allows moving from the local repository to upstream repository, only if you have the permission (e.g. if it is yours)  

*git fetch*: update local repository to  be like the upstream repository, from upstream to local  

*git merge*: make the updated local sync with the working directory and staging area  

To change everything in one shot (from upstream to working dir), use *git pull* (equivalent to combining *git fetch* + *git merge*)  


### Creating a GitHub Repository

Recap: two ways to get started, one is cloning an existing repository, the other is initializing our own  

Create our own project on our computer (independent of Git) on our own machine
Create an upstream repo on Github, copy repo's url  

Make a local git repository: On the local machine, in the project directory, use *git init*. Now git starts tracking everything in the local repo.  

Now we need to start moving files into our local repo and connect local repo to the upstream remote by *git remote* add *origin <url>*  

**Note**: The first time you push to a new repository, you may also need to use these *git push* options: *git push --set-upstream origin master*. If you need to run these arguments but forget to do so, you will get an error with a reminder.  


## Comprehension Check: Git and GitHub

### Q1

Which statement describes reasons why we recommend using git and Github when working on data analysis projects?  

**Possible Answers**  

* Git and GitHub facilitate fast, high-throughput analysis of large data sets.  

* Git and GitHub allow easy version control, collaboration, and resource sharing.  

* Git and GitHub have graphical interfaces that make it easy to learn to code in R.  

* Git and GitHub is good for long-term storage of private data.  

**ANSWER: **  


### Q2

Select the steps necessary to:

1. Create a directory called “project-clone”,  

2. Clone the contents of a git repo at the following URL into that directory (https://github.com/user123/repo123.git), and  

3. List the contents of the cloned repo.  


**Possible Answers**  

mkdir project-clone
git add https://github.com/user123/repo123.git
ls
 
mkdir project-clone
git clone https://github.com/user123/repo123.git
ls
 
mkdir project-clone
cd project-clone
git clone https://github.com/user123/repo123.git
ls
 
mkdir project-clone
cd project-clone
git clone https://github.com/user123/repo123.git
less

**ANSWER: **  


### Q3

You have successfully cloned a GitHub repository onto your local system. The cloned repository contains a file called “heights.txt” that lists the heights of students in a class. One student was missing from the dataset, so you add that student’s height using the following command:  

echo “165” >> heights.txt
Next you enter the command git status to check the status of the Github repository.  

What message is returned and what does it mean?  

**Possible Answers**  

*modified: heights.txt, no changes added to commit*
This message means that the heights.txt file was modified, but the changes have not been staged or committed to the local repository.  

*modified: heights.txt, no changes added to commit*
This message means that the heights.txt file was modified and staged, but not yet committed.  

*1 file changed*
This message means that the heights.txt file was modified, staged, committed, and pushed to the upstream repository.  

*modified: heights.txt*
This message means that the heights.txt file was modified, staged, and committed.  

**ANSWER: **  


### Q4

You cloned your own repository and modified a file within it on your local system. Next, you executed the following series of commands to include the modified file in the upstream repository, but it didn’t work. Here is the code you typed:  

*git add modified_file.txt*  

*git commit -m “minor changes to file” modified_file.txt*  

*git pull*  

What is preventing the modified file from being added to the upstream repository?  

**Possible Answers**  

* The wrong option is being used to add a descriptive message to the commit.  

* git push should be used instead of git pull.  

* git commit should come before git add.  

* The git pull command line needs to include the file name.  

**ANSWER: **  


### Q5

You have a directory of scripts and data files on your computer that you want to share with collaborators using GitHub. You create a new repository on your GitHub account called “repo123” that has the following URL: https://github.com/user123/repo123.git  

Which of the following sequences of commands will convert the directory on your computer to a GitHub directory and create and add a descriptive “read me” file to the new repository?  

**Possible Answers**  

git init
git add README.txt
git commit -m "First commit. Adding README file."
git remote add origin `https://github.com/user123/repo123.git`
git push
 
echo “A new repository with my scripts and data” > README.txt
git init
git add
git commit -m "First commit. Adding README file."
git remote add origin `https://github.com/user123/repo123.git`
git push
 
echo “A new repository with my scripts and data” > README.txt
git init
git add README.txt
git commit -m "First commit. Adding README file."
git remote add origin `https://github.com/user123/repo123.git`
git pull
 
echo “A new repository with my scripts and data” > README.txt
git init
git add README.txt
git commit -m "First commit. Adding README file."
git remote add origin `https://github.com/user123/repo123.git`
git push

**ANSWER: **  


### Q6

You have made a local change to a file in your R project, which is associated with a GitHub repository. You add your changes and push, but you receive a message:

*Everything up-to-date*  

Which of the following commands did you forget to do?

**Possible Answers**  

* git pull  

* git merge  

* git add  

* git fetch  

* git commit  

* git push  

* git rebase  


**ANSWER: **  


### Q7

Suppose you previously cloned a repository with *git clone*. Running *git status* shows:  

On branch master
Your branch is up to date with 'origin/master'.

	nothing to commit, working tree clean

However, you know that there are some changes in the upstream repository.  

How will you sync these changes with one command?  

**Possible Answers**  

* git fetch  

* git pull  

* git merge origin/master  

* git merge upstream/master  

* git push  

**ANSWER: **  


