---
title: 'Productivity Tools Section 3: Reproducible Reports'
author: "Erin Lloyd"
date: "29/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 3.1 Reproducible Reports

### Reproducible Reports with R Markdown

The final output is usually a report, textual descriptions and figures, and tables.  

The aim is to generate a reproducible report in R markdown and knitr.  

Features of Rmarkdown: code and text can be combined to the same document and figures and tables are automatically added to the file.  


### R Markdown

R Markdown is a format for *literate programming* documents. Literate programming weaves instructions, documentation and detailed comments in between machine executable code, producing a document that describes the program that is best for human understanding.  

Start an R markdown document by clicking on File > New File > the R Markdown. 

The output could be HTML, PDF, or Microsoft Word, which can be changed in the header output, e.g. pdf_document / html_document/p>  


### knitr

The **knitr** package is used to compile R markdown documents.  

The first time you click the "knit" button on the editor pane a pop-up window will prompt you to install packages, but after that is completed, the button will automatically knit your document.  

*github_document* gives a .md file, which will give the best presentation on GitHub.  


## Comprehension Check: Reproducible Reports

### Q1

Why might you want to create a report using R Markdown?  

**Possible Answers**  

* R Markdown has better spell-checking tools than other word processors.  

* R Markdown allows you to automatically add figures to the final document.  

* R Markdown final reports have smaller file sizes than Word documents.  

* R Markdown documents look identical to the final report.  

**ANSWER: **  


### Q2

You have a vector of student heights called heights. You want to generate a histogram of these heights in a final report, but you don’t want the code to show up in the final report. You want to name the R chunk “histogram” so that you can easily find the chunk later.  

Which of the following R chunks does everything you want it to do?  

**Possible Answers**  


**ANSWER: **  


### Q3

Below is a section of R Markdown code that generates a report.  

    
Select the statement that describes the file report generated by the R markdown code above.  

**Possible Answers**  

* A PDF document called “Final Grade Distribution” that prints a summary of the “grades” object. The code to load the file and produce the summary will not be included in the final report.  

* A PDF document called “Final Grade Distribution” that prints a summary of the “grades” object. The code to load the file and produce the summary will be included in the final report.  

* An HTML document called “Final Grade Distribution” that prints a summary of the “grades” object. The code to load the file and produce the summary will not be included in the final report.  

* A PDF document called “Final Grade Distribution” that is empty because the argument echo=FALSE was used.  

**ANSWER: **  


### Q4

The user specifies the output file format of the final report when using R Markdown.  

Which of the following file types is NOT an option for the final output?  

**Possible Answers**  

*.rmd  

*.pdf  

*.doc  

*.html. 

**ANSWER: **  


### Q5
    
What will be the output for the above Rmarkdown file when knit to HTML?  

**Possible Answers**  

* The only output is the text: Here 32 cars are compared.  

* Since we have echo=F, the code chunk is not evaluated, therefore we will have both the code and the text: Here 'r n' cars are compared.  

* The code will be displayed as well as Here 32 cars are compared.  

* R cannot comprehend the value of n, we will get an error.  

**ANSWER: **  
